[Node] add `-x` to initContainers
paritytech/helm-charts pull request #107
Opened 2022-07-01 17:31 UTC by BulatSaif

1. We have `echo` to print debug messages but sometimes it is not enough to understand which command failed, adding `-x` will fix it.

`-x` added to all initContainers, except `inject-vault-keys`, since key used in command line. 
 
2. Removed `apk add --no-cache wget` since alpine container already has wget

2022-07-01 17:38 UTC, dblane-digicatapult requested changes
Maybe have this optionally set using a helm value like 'debugInitContainers' instead of setting as a default.

2022-07-01 18:02 UTC, BulatSaif commented
> Maybe have this optionally set using a helm value like 'debugInitContainers' instead of setting as a default.

Thanks, this is good Idea

2022-07-04 05:40 UTC, ArshamTeymouri approved these changes

2022-07-04 08:52 UTC, PierreBesson approved these changes

2022-07-04 08:53 UTC, merged