Draft: Refactor perNodeServices options and alllow setting the p2p service type
paritytech/helm-charts pull request #63
Opened 2022-03-18 11:02 UTC by PierreBesson

2022-03-18 11:11 UTC, dblane-digicatapult requested changes

2022-03-18 11:11 UTC, dblane-digicatapult commented on charts/node/templates/service.yaml
> +  {{- end }}
Could use `else if eq` for these and skip the unnecessary `-ends`

2022-03-18 11:11 UTC, dblane-digicatapult commented on charts/node/templates/service.yaml
> +  {{- end }}
Could use `else if eq` for these and skip the unnecessary `-ends`

2022-03-18 23:59 UTC, dblane-digicatapult commented
How are you planning to deal with `--public-addr` service address/IP lookup?

I have a rudimentary implementation for my use case (AWS loadbalancer) however this then means advertising `dns4` multiaddr format instead of `ipv4`

The case for loadbalancers is fairly difficult and extremely provider specific and I'm fairly certain there is no "one size fits all" solution.  From memory most of the PaaS providers I tested with advertise the address on either `status.loadbalancer.ingress.ip[]` or `status.loadbalancer.ingress.hostname` So we could try looking up both?

2022-03-19 10:13 UTC, PierreBesson commented
> How are you planning to deal with --public-addr service address/IP lookup?

Yes adding the ability to set the loadBalancer IP or hostname would be good. If you want to give it a shot in a following PR it would be very appreciated. We can support any cloud specific way to do this as long as there are users which need this support.

2022-03-19 18:52 UTC, dblane-digicatapult commented
> Yes adding the ability to set the loadBalancer IP or hostname would be good. If you want to give it a shot in a following PR it would be very appreciated. We can support any cloud specific way to do this as long as there are users which need this support.

Currently we pass the NodePort `RELAY_CHAIN_P2P_PORT`, `PARA_CHAIN_P2P_PORT` and `EXTERNAL_IP` to the container via a file on the data volume.
Do you want to continue with this approach or should we instead create a configmap which we then do a `kubectl patch` against in the init container? The advantage of using the configmap is that it can be queried by other containers and applications and has potential use for declaring bootnodes and other nodes dynamically.  The disadvantage is that anyone using GitOps tooling to maintain state will have to not overwrite these patches.

Thoughts?

2022-03-21 17:22 UTC, PierreBesson commented
>Do you want to continue with this approach or should we instead create a configmap which we then do a kubectl patch against in the init container? The advantage of using the configmap is that it can be queried by other containers and applications and has potential use for declaring bootnodes and other nodes dynamically. The disadvantage is that anyone using GitOps tooling to maintain state will have to not overwrite these patches.

I don't like the approach of using `kubectl patch` directly from the pod. The Kubernetes resource should be the declarative source of truth and should not be modified by init containers. Also GitOps can be pretty much expected. For bootnodes, people should use something like a fixed `nodePort` even though in this case you can only have one replica.

@dblane-digicatapult, it would be better to have this discussion in the issue: https://github.com/paritytech/helm-charts/issues/29

2022-03-22 13:58 UTC, BulatSaif approved these changes

2022-03-23 11:12 UTC, merged